version: "3"
services:
  admin: # admin panel
    build:
      context: ./
      dockerfile: Admin.Dockerfile
    ports:
      - 9002:80
    environment: # not in use until official introduction of IConfiguration in Blazor by Microsoft
      - API_ENDPOINT=http://api.gateway/ # to provide production API_ENDPOINT use appsettings.json in Admin/

  public:  # front-end
    build:
      context: ./
      dockerfile: Public.Dockerfile
    ports:
      - 9001:80
    environment:
      - API_ENDPOINT=http://api.gateway/

  api.gateway: # api gateway
    build:
      context: ./
      dockerfile: Api.Gateway.Dockerfile
    ports:
      - 9000:80

  api: # api service
    build:
      context: ./
      dockerfile: Api.Dockerfile
    ports:
      - 9003:80 # should be >= 9003/service
    env_file:
      - ./app.env