version: "3"
services:
  college.admin: # admin panel
    build:
      context: ./
      dockerfile: Admin.Dockerfile
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:admin-college.xoredge.com
    environment: # not in use until official introduction of IConfiguration in Blazor by Microsoft
      - API_ENDPOINT=http://college.api/ # to provide production API_ENDPOINT use appsettings.json in Admin/
    networks:
      - services-network

  college.public:  # front-end
    build:
      context: ./
      dockerfile: Public.Dockerfile
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:college.xoredge.com
    environment:
      - API_ENDPOINT=http://college.api/
    networks:
      - services-network

  college.api:  # web api
    build:
      context: ./
      dockerfile: Api.Dockerfile
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:api-college.xoredge.com
    env_file:
      - ./api.env
    networks:
      - services-network

networks:
  services-network:
    external: true