version: "3"
services:
  web.admin:
    build: ./Admin/
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:admin.localhost
    env_file:
      - ./Admin/app.env
    #################################################################################################
    #
    # Below - developers don't need to modify the network definition, unless asked by the sysadmin.
    #
    ##################################################################################################

    networks:
      # This 'uses' the proxy-net / services-network
      - services-network
  web.public:
    build: ./Public/
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:public.localhost
    env_file:
      - ./Public/app.env
    #################################################################################################
    #
    # Below - developers don't need to modify the network definition, unless asked by the sysadmin.
    #
    ##################################################################################################

    networks:
      # This 'uses' the proxy-net / services-network
      - services-network
  web.api:
    build: ./Api/
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:api.localhost
    env_file:
      - ./Api/app.env
    #################################################################################################
    #
    # Below - developers don't need to modify the network definition, unless asked by the sysadmin.
    #
    ##################################################################################################

    networks:
      # This 'uses' the proxy-net / services-network
      - services-network

networks:
  services-network:
    external: true
