version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - DB_HOST=${DB_HOST_PGS}
      - DB_USER=${DB_USER_PGS}
      - DB_PASS=${DB_PASS_PGS}
      - DB_NAME=${DB_NAME_API}
      - API_KEY=${API_KEY}
      - SUPER_USER=${SUPER_USER}
      - SUPER_PASS=${SUPER_PASS}
    depends_on:
      - rabbitmq

  api.gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Api.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://0.0.0.0:80
    depends_on:
      - rabbitmq
      - api

  admin:
    image: ${DOCKER_REGISTRY-}admin
    build:
      context: .
      dockerfile: Admin/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - API_ENDPOINT=http://api.gateway/ # not in use. to provide API_ENDPOINT use appsettings.json in Admin/
    depends_on:
      - api.gateway

  public:
    image: ${DOCKER_REGISTRY-}public
    build:
      context: .
      dockerfile: Public/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - API_ENDPOINT=http://api.gateway/
    depends_on:
      - api.gateway