version: "3"
services:
  web.admin:
    build:
      context: ./
      dockerfile: Admin.Dockerfile
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:admin.localhost
    env_file:
      - ./admin.env
    #################################################################################################
    #
    # Below - developers don't need to modify the network definition, unless asked by the sysadmin.
    #
    ##################################################################################################

    networks:
      # This 'uses' the proxy-net / services-network
      - services-network
  web.public:
    build:
      context: ./
      dockerfile: Public.Dockerfile
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:public.localhost
    env_file:
      - ./public.env
    #################################################################################################
    #
    # Below - developers don't need to modify the network definition, unless asked by the sysadmin.
    #
    ##################################################################################################

    networks:
      # This 'uses' the proxy-net / services-network
      - services-network
  web.api:
    build:
      context: ./
      dockerfile: Api.Dockerfile
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:api.localhost
    env_file:
      - ./api.env
    #################################################################################################
    #
    # Below - developers don't need to modify the network definition, unless asked by the sysadmin.
    #
    ##################################################################################################

    networks:
      # This 'uses' the proxy-net / services-network
      - services-network

networks:
  services-network:
    external: true
